# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Marvelsbot5Agent
  demands:
   - agent.name -equals Marvels-bot5

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'MarvelsbotOrch'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'MarvelsbotOrch'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Shared'
    entryPoints: 'Main.xaml'
